services:
  db:
    image: postgres:16
    container_name: django_db
    environment:
      - POSTGRES_DB=produtos_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: